### ISSUE TITLE
RELEASE_HEAD.md:  No such file or directory

### ISSUE THREAD

**Issue by mofm** [CSchoel/release-notes-from-changelog#1]
Even though there is a RELEASE_HEAD.md file, I am getting the error as below:

```
cp: cannot stat 'RELEASE_HEAD.md: No such file or directory
Error: Process completed with exit code 1.
```

workflow:
```
- name: Checkout this repository
  uses: actions/checkout@v2
  with:
      path: my-repo
- name: Release Notes
  uses: CSchoel/release-notes-from-changelog@v1
```
