### ISSUE TITLE
Rolling release action - how to?

### ISSUE THREAD

**Issue by rusak47** [CSchoel/release-notes-from-changelog#2]
Hello!

I've recently found this action, and it looks great. Thank you for that.
However, i'm new to git actions and i can't make it to work properly.

I have created .github/workflows/this_action.yaml with contents:
```
name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "greet"
  build:
    name: "My fancy build"
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: CSchoel/release-notes-from-changelog@v1
       # with:
        #  version: 1.1.8
      # Runs a single command using the runners shell
      - name: Create Release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create
          -d
          -F RELEASE.md
          -t "Version $RELEASE_VERSION"
          ${GITHUB_REF#refs/*/}
          ps3-cloud-drive.pkg
```

I've re-formatted [my changelog](https://github.com/diabolusss/ps3-cloud-drive/blob/master/CHANGELOG.md) to meet the mentioned standard, and calling action with input "with version: 1.1.8" actually finds a changelog entry for the selected version.
Without "with version" input, release is generated with header only. 

- am i missing something?
- is it possible to make release with latest version from changelog without specifying it in action file and how?
